name: main

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Init workflowj
jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: check-changed-files
    outputs:
      frontend_changed: ${{ steps.frontend_changed.outputs.has_changes }}
      backend_changed: ${{ steps.backend_changed.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: backend_changes
        uses: tj-actions/changed-files@v10.1
        with:
         files: |
            backend

      - name: Get changed files
        id: frontend_changes
        uses: tj-actions/changed-files@v10.1
        with:
         files: |
            frontend

      - name: List all backend changes files
        id: backend_changed
        run: |
          if [[  -n "${{ steps.backend_changes.outputs.all_changed_and_modified_files }}" ]]; then 
            echo ::set-output name=has_changes::${{ toJSON(true) }}
          else
            echo ::set-output name=has_changes::${{ toJSON(false) }}
           fi

      - name: List all frontend changes files
        id: frontend_changed
        run: |
          if [[ -n "${{ steps.frontend_changes.outputs.all_changed_and_modified_files }}" ]]; then 
            echo ::set-output name=has_changes::${{ toJSON(true) }}
          else
            echo ::set-output name=has_changes::${{ toJSON(false) }}
           fi

  be_build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: check if be changed
    if: ${{ fromJSON(needs.build.outputs.backend_changed) }}
    needs: build
    steps:
      - name: log if changed files
        id: backend_changes
        run: |
            echo "frontend:" ${{ fromJSON(needs.build.outputs.frontend_changed) }}
            echo "backend:" ${{ fromJSON(needs.build.outputs.backend_changed) }}
      - name: fail the build
        run: |
            exit 1
  
  fe_build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: check if fe changed
    needs: build
    if: ${{ fromJSON(needs.build.outputs.frontend_changed) }}
    steps:
      - name: log if changed files
        id: backend_changes
        run: |
            echo "frontend:" ${{ fromJSON(needs.build.outputs.frontend_changed) }}
            echo "backend:" ${{ fromJSON(needs.build.outputs.backend_changed) }}

  be_build_extra:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: be extra run
    needs: [be_build]
    steps:
      - name: log if changed files
        run: |
            echo completed
  fe_build_extra:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: fe extra run 
    needs: [fe_build]
    steps:
      - name: log if changed files
        run: |
            echo completed
  
  # Aggregate build results for required builds 
  main-completion-status:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: alert changed
    needs: [fe_build_extra, be_build_extra, be_build]
    if: always()
    steps:
      - name: log if changed files
        run: |
            echo completed
      - name: consider failing build
        if: contains(needs.fe_build_extra.result , 'failure') || contains(needs.fe_build_extra.result , 'cancelled') || contains(needs.be_build_extra.result, 'failure') || contains(needs.be_build_extra.result, 'cancelled') || contains(needs.be_build.result, 'failure') || contains(needs.be_build.result, 'cancelled')
        run: |
            exit 1
