name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: backend_changes
        uses: tj-actions/changed-files@v10.1
        with:
         files: |
            backend

      - name: Get changed files
        id: frontend_changes
        uses: tj-actions/changed-files@v10.1
        with:
         files: |
            frontend

      - name: List all backend changes files
        run: |
          for file in ${{ steps.backend_changes.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified"
          done

      - name: List all frontend changes files
        run: |
          for file in ${{ steps.frontend_changes.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified"
          done